sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=drf{35,36}-py{27}-dj{108,109,111}-esdsl{6,7}
  - python: "3.6"
    env: TOX_ENV=drf{37,36}-py36-dj111-esdsl{6,7}
  - python: "3.8"
    env: TOX_ENV=drf{310,311}-py38-dj{200,300}-esdsl{6,7}
install:
  - pip install --upgrade pip
  - pip install tox-travis
before_script:
  - sleep 30 # elasticsearch starting time
script:
  - tox
services:
  - elasticsearch
